"on":
  push:
    branches:
    - loader
name: Deploy to az16-own-the-internet
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Setup porter
      uses: porter-dev/setup-porter@v0.1.0
    - name: Deploy stack
      timeout-minutes: 30
      run: exec porter apply
      env:
        PORTER_CLUSTER: "4197"
        PORTER_DEPLOYMENT_TARGET_ID: 5395c8d0-0040-4594-995a-5e1ee8fd7208
        PORTER_HOST: https://dashboard.porter.run
        PORTER_PR_NUMBER: ${{ github.event.number }}
        PORTER_PROJECT: "12227"
        PORTER_REPO_NAME: ${{ github.event.repository.name }}
        PORTER_STACK_NAME: az16-own-the-internet
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_12227_4197 }}
